# Copyright (C) 2018 Takezoe,Tomoaki <tomoaki3478@res.ac>
#
# SPDX-License-Identifier: LGPL-3.0-or-later

[package]
name = "mullos"
version = "0.1.0"
authors = ["Takezoe,Tomoaki <tomoaki3478@res.ac>"]

[dependencies]
